import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import DefaultLoading from "@/components/loading/default-loading";

const defaultFont = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${defaultFont.className} overflow-x-hidden`}
      >
        <Suspense fallback={<DefaultLoading />}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="px-4">{children}</div>

            <Toaster richColors />
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
